# Generated by Django 5.2.17 on 2026-09-25 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rastreamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkDispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('expira_em', models.DateTimeField()),
                ('utilizado_em', models.DateTimeField(blank=True, null=True)),
                ('revogado_em', models.DateTimeField(blank=True, null=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_envio', to='rastreamento.dispositivo')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
