# Generated by Django 5.2.17 on 2026-09-26 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rastreamento', '0002_linkdispositivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='localizacao',
            name='autorizacao_recebida_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='localizacao',
            name='autorizacao_texto',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='localizacao',
            name='autorizacao_versao',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='localizacao',
            name='canal_envio',
            field=models.CharField(choices=[('legado', 'Sem registro de autorização'), ('api', 'API autenticada'), ('sessao', 'Sessão autenticada'), ('link', 'Link temporário')], default='legado', max_length=16),
        ),
    ]
